# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  db:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=pechatnik
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
     # Задание имени контейнера для сервиса pgdb
    container_name: db
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  pgdbdata: null
