# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
     # Задание имени контейнера для сервиса pgdb
    container_name: db
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
      - web

volumes:
  pgdbdata:
  static:
  media:
