# Generated by Django 5.2.5 on 2025-08-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceview',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
