# Generated by Django 5.2.5 on 2025-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_views', '0002_alter_priceview_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('phone', models.TextField(blank=True, max_length=22, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whats_app_link', models.URLField()),
                ('instagram_app_link', models.URLField()),
            ],
        ),
    ]
