# Generated by Django 5.2.5 on 2025-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_views', '0003_contactview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactview',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='priceview',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
