# Generated by Django 5.2.5 on 2025-09-03 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_views', '0004_contactview_isactive_priceview_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingPrintView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('advantages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
